-- Insert dummy tenant data for the last 90 days
INSERT INTO tenants (name, data_usage, date) VALUES
-- Existing tenants with extended data
('RUDRA', 22.4, CURRENT_DATE - 89),
('Vashi Office', 34.5, CURRENT_DATE - 89),
('Station Satcom', 64.2, CURRENT_DATE - 89),
('RUDRA', 25.1, CURRENT_DATE - 88),
('Vashi Office', 36.8, CURRENT_DATE - 88),
('Station Satcom', 68.9, CURRENT_DATE - 88),
('RUDRA', 23.7, CURRENT_DATE - 87),
('Vashi Office', 35.2, CURRENT_DATE - 87),
('Station Satcom', 65.8, CURRENT_DATE - 87),
('RUDRA', 24.3, CURRENT_DATE - 86),
('Vashi Office', 37.1, CURRENT_DATE - 86),
('Station Satcom', 67.5, CURRENT_DATE - 86),
('RUDRA', 26.8, CURRENT_DATE - 85),
('Vashi Office', 38.4, CURRENT_DATE - 85),
('Station Satcom', 69.2, CURRENT_DATE - 85),
('RUDRA', 25.5, CURRENT_DATE - 84),
('Vashi Office', 36.9, CURRENT_DATE - 84),
('Station Satcom', 66.7, CURRENT_DATE - 84),
('RUDRA', 27.2, CURRENT_DATE - 83),
('Vashi Office', 39.1, CURRENT_DATE - 83),
('Station Satcom', 70.3, CURRENT_DATE - 83),

-- New tenants with data for the last 30 days
('Mumbai HQ', 45.2, CURRENT_DATE - 29),
('Bangalore Branch', 38.7, CURRENT_DATE - 29),
('Delhi Office', 42.1, CURRENT_DATE - 29),
('Hyderabad Center', 35.8, CURRENT_DATE - 29),
('Chennai Unit', 40.3, CURRENT_DATE - 29),
('Mumbai HQ', 47.5, CURRENT_DATE - 28),
('Bangalore Branch', 40.2, CURRENT_DATE - 28),
('Delhi Office', 43.8, CURRENT_DATE - 28),
('Hyderabad Center', 37.1, CURRENT_DATE - 28),
('Chennai Unit', 41.9, CURRENT_DATE - 28),
('Mumbai HQ', 46.8, CURRENT_DATE - 27),
('Bangalore Branch', 39.5, CURRENT_DATE - 27),
('Delhi Office', 44.2, CURRENT_DATE - 27),
('Hyderabad Center', 36.4, CURRENT_DATE - 27),
('Chennai Unit', 42.7, CURRENT_DATE - 27),

-- Recent data for all tenants (last 7 days)
('RUDRA', 22.4, CURRENT_DATE - 6),
('Vashi Office', 34.5, CURRENT_DATE - 6),
('Station Satcom', 64.2, CURRENT_DATE - 6),
('Mumbai HQ', 48.3, CURRENT_DATE - 6),
('Bangalore Branch', 41.6, CURRENT_DATE - 6),
('Delhi Office', 45.7, CURRENT_DATE - 6),
('Hyderabad Center', 38.2, CURRENT_DATE - 6),
('Chennai Unit', 43.5, CURRENT_DATE - 6),

('RUDRA', 25.1, CURRENT_DATE - 5),
('Vashi Office', 36.8, CURRENT_DATE - 5),
('Station Satcom', 68.9, CURRENT_DATE - 5),
('Mumbai HQ', 49.1, CURRENT_DATE - 5),
('Bangalore Branch', 42.8, CURRENT_DATE - 5),
('Delhi Office', 46.3, CURRENT_DATE - 5),
('Hyderabad Center', 39.4, CURRENT_DATE - 5),
('Chennai Unit', 44.8, CURRENT_DATE - 5),

('RUDRA', 23.7, CURRENT_DATE - 4),
('Vashi Office', 35.2, CURRENT_DATE - 4),
('Station Satcom', 65.8, CURRENT_DATE - 4),
('Mumbai HQ', 47.6, CURRENT_DATE - 4),
('Bangalore Branch', 40.9, CURRENT_DATE - 4),
('Delhi Office', 44.5, CURRENT_DATE - 4),
('Hyderabad Center', 37.8, CURRENT_DATE - 4),
('Chennai Unit', 42.1, CURRENT_DATE - 4),

('RUDRA', 24.3, CURRENT_DATE - 3),
('Vashi Office', 37.1, CURRENT_DATE - 3),
('Station Satcom', 67.5, CURRENT_DATE - 3),
('Mumbai HQ', 48.7, CURRENT_DATE - 3),
('Bangalore Branch', 41.3, CURRENT_DATE - 3),
('Delhi Office', 45.2, CURRENT_DATE - 3),
('Hyderabad Center', 38.6, CURRENT_DATE - 3),
('Chennai Unit', 43.9, CURRENT_DATE - 3),

('RUDRA', 26.8, CURRENT_DATE - 2),
('Vashi Office', 38.4, CURRENT_DATE - 2),
('Station Satcom', 69.2, CURRENT_DATE - 2),
('Mumbai HQ', 50.2, CURRENT_DATE - 2),
('Bangalore Branch', 43.5, CURRENT_DATE - 2),
('Delhi Office', 47.1, CURRENT_DATE - 2),
('Hyderabad Center', 40.3, CURRENT_DATE - 2),
('Chennai Unit', 45.6, CURRENT_DATE - 2),

('RUDRA', 25.5, CURRENT_DATE - 1),
('Vashi Office', 36.9, CURRENT_DATE - 1),
('Station Satcom', 66.7, CURRENT_DATE - 1),
('Mumbai HQ', 49.5, CURRENT_DATE - 1),
('Bangalore Branch', 42.1, CURRENT_DATE - 1),
('Delhi Office', 46.8, CURRENT_DATE - 1),
('Hyderabad Center', 39.7, CURRENT_DATE - 1),
('Chennai Unit', 44.3, CURRENT_DATE - 1),

('RUDRA', 27.2, CURRENT_DATE),
('Vashi Office', 39.1, CURRENT_DATE),
('Station Satcom', 70.3, CURRENT_DATE),
('Mumbai HQ', 51.4, CURRENT_DATE),
('Bangalore Branch', 44.2, CURRENT_DATE),
('Delhi Office', 48.5, CURRENT_DATE),
('Hyderabad Center', 41.8, CURRENT_DATE),
('Chennai Unit', 46.7, CURRENT_DATE);

-- Insert dummy audit trail data
INSERT INTO audit_trail (time, description, event, category, performed_by) VALUES
('2024-02-11 14:33:00', 'Admin user Roshann Agarwal with the role Tenant Admin was created', 'create', 'Admin', 'Fletcher Fernandes'),
('2024-02-11 13:52:00', 'A firewall rule allowing traffic from IP addresses to be accepted was created.', 'create', 'Firewall Rule', 'Sachin Gowda'),
('2024-02-11 13:23:00', 'Certificate downloaded for router Tranquil Sea.', 'download', 'Router Certificate', 'Mukesh Sai Kumar'),
('2024-02-11 13:11:00', 'Hotspot user JohnDoe was deleted from router Mianzimu (HCQ083QNSNF).', 'delete', 'Hotspot User', 'Vishal Dubey'),
('2024-02-11 13:01:00', 'Firewall template Dualog was deleted', 'delete', 'Firewall Template', 'Vishal Dubey'),
('2024-02-11 12:58:00', 'New router RUDRA23 (FF044QNSNF) was created', 'create', 'Router', 'Karan Sajnani'),
('2024-02-11 12:58:00', 'New router RUDRA23 (FF044QNSNF) was created', 'create', 'Router', 'Karan Sajnani'),
('2024-02-11 12:58:00', 'New router RUDRA23 (FF044QNSNF) was created', 'create', 'Router', 'Karan Sajnani'),
('2024-02-11 12:58:00', 'New router RUDRA23 (FF044QNSNF) was created', 'create', 'Router', 'Karan Sajnani'),
('2024-02-11 12:58:00', 'New router RUDRA23 (FF044QNSNF) was created', 'create', 'Router', 'Karan Sajnani'),
('2024-02-11 12:58:00', 'New router RUDRA23 (FF044QNSNF) was created', 'create', 'Router', 'Karan Sajnani');

-- Insert dummy data for data_exchanged
INSERT INTO data_exchanged (total_data, date) VALUES
(80.4, CURRENT_DATE);

-- Insert dummy data for fleets
INSERT INTO fleets (name) VALUES
('Fleet A'),
('Fleet B'),
('Fleet C'),
('Fleet D'),
('Fleet E'),
('Fleet F'),
('Fleet G'),
('Fleet H'),
('Fleet I'),
('Fleet J'),
('Fleet K'),
('Fleet L'),
('Fleet M'),
('Fleet N'),
('Fleet O'),
('Fleet P'),
('Fleet Q'),
('Fleet R'),
('Fleet S'),
('Fleet T'),
('Fleet U'),
('Fleet V'),
('Fleet W'),
('Fleet X'),
('Fleet Y'),
('Fleet Z'),
('Fleet AA'),
('Fleet BB'),
('Fleet CC'),
('Fleet DD'),
('Fleet EE'),
('Fleet FF'),
('Fleet GG'),
('Fleet HH'),
('Fleet II'),
('Fleet JJ'),
('Fleet KK'),
('Fleet LL'),
('Fleet MM'),
('Fleet NN'),
('Fleet OO'),
('Fleet PP'),
('Fleet QQ'),
('Fleet RR'),
('Fleet SS');

-- Insert dummy data for hotspot_users
INSERT INTO hotspot_users (username, is_active) VALUES
('user1', true),
('user2', true),
('user3', false),
('user4', true),
('user5', false),
('user6', true),
('user7', true),
('user8', false),
('user9', true),
('user10', true),
('user11', false),
('user12', true),
('user13', true),
('user14', false),
('user15', true),
('user16', true),
('user17', false),
('user18', true),
('user19', true),
('user20', false),
('user21', true),
('user22', true),
('user23', false);

-- Insert dummy data for routers
INSERT INTO routers (name, is_online) VALUES
('Router1', true),
('Router2', true),
('Router3', false),
('Router4', true),
('Router5', false),
('Router6', true),
('Router7', true),
('Router8', false),
('Router9', true),
('Router10', false),
('Router11', true),
('Router12', true),
('Router13', false),
('Router14', true),
('Router15', true),
('Router16', false),
('Router17', true),
('Router18', true),
('Router19', false),
('Router20', true),
('Router21', true),
('Router22', false),
('Router23', true),
('Router24', true),
('Router25', false),
('Router26', true),
('Router27', true),
('Router28', false),
('Router29', true),
('Router30', true),
('Router31', false),
('Router32', true),
('Router33', true),
('Router34', false),
('Router35', true); 